name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت کد منبع
        uses: actions/checkout@v3

      - name: نصب پایتون
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: نصب وابستگی‌ها
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython

      - name: ساخت APK
        run: |
          buildozer -v android debug

      - name: آپلود فایل APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
